updated files for 1.0.28 release
git-svn-id: http://svn.code.sf.net/p/qmailadmin/code/trunk@56 0199c96e-5249-4d07-b9ae-b85610bb9a6e

diff --git a/qmailadmin/configure b/qmailadmin/configure
--- a/qmailadmin/configure
+++ b/qmailadmin/configure
@@ -18,9 +18,9 @@ ac_help="$ac_help
 ac_help="$ac_help
   --enable-cgibindir={dir}  HTTP server's cgi-bin directory."
 ac_help="$ac_help
-  --enable-imagedir={dir}   Where to put the image files [DocumentRoot/images/qmailadmin]."
-ac_help="$ac_help
   --enable-imageurl={url}   URL to image files [/images/qmailadmin]."
+ac_help="$ac_help
+  --enable-imagedir={dir}   Where to put the image files [DocumentRoot/images/qmailadmin]."
 ac_help="$ac_help
   --enable-htmllibdir={dir} qmailadmin HTML library directory."
 ac_help="$ac_help
@@ -846,7 +846,7 @@ echo "$ac_t""$host" 1>&6
 
 
 QA_PACKAGE="qmailadmin"
-QA_VERSION="1.0.27"
+QA_VERSION="1.0.28"
 
 cat >> confdefs.h <<EOF
 #define QA_PACKAGE "$QA_PACKAGE"
@@ -1554,7 +1554,7 @@ fi
 
 cgibindir=""
 
-for f in /home/httpd /usr/local/apache /usr/local/www /var/lib/httpd /var/www /usr/local/www 
+for f in /home/httpd /usr/local/apache /usr/local/www /var/lib/httpd /var/www /usr/local/www $htmldir
 do
     if test -d $f/cgi-bin
     then
@@ -1571,29 +1571,6 @@ else
         if test "$cgibindir" = ""
         then
             { echo "configure: error: Unable to find your cgi-bin directory, specify --enable-cgibindir." 1>&2; exit 1; }
-        fi
-     
-fi
-
-
-
-imagedir=""
-for f in /home/httpd/html /usr/local/apache/htdocs /usr/local/www/data /var/www/html
-do
-    if test -d $f
-    then
-        imagedir=$f/images/qmailadmin
-    fi
-done
-# Check whether --enable-imagedir or --disable-imagedir was given.
-if test "${enable_imagedir+set}" = set; then
-  enableval="$enable_imagedir"
-  imagedir="$enableval"
-else
-  
-        if test "$imagedir" = ""
-        then
-            { echo "configure: error: Unable to find your html image directory, specify --enable-imagedir." 1>&2; exit 1; }
         fi
      
 fi
@@ -1620,12 +1597,34 @@ cat >> confdefs.h <<EOF
 EOF
 
 
+imagedir=""
+for f in /home/httpd/html /usr/local/apache/htdocs /usr/local/www/data /var/www/html $htmldir
+do
+    if test -d $f
+    then
+        imagedir=$f$imageurl
+    fi
+done
+# Check whether --enable-imagedir or --disable-imagedir was given.
+if test "${enable_imagedir+set}" = set; then
+  enableval="$enable_imagedir"
+  imagedir="$enableval"
+else
+  
+        if test "$imagedir" = ""
+        then
+            { echo "configure: error: Unable to find your html image directory, specify --enable-imagedir." 1>&2; exit 1; }
+        fi
+     
+fi
+
+
 
 htmllibdir="/usr/local/share/qmailadmin/"
 
-# Check whether --with-htmllibdir or --without-htmllibdir was given.
-if test "${with_htmllibdir+set}" = set; then
-  withval="$with_htmllibdir"
+# Check whether --enable-htmllibdir or --disable-htmllibdir was given.
+if test "${enable_htmllibdir+set}" = set; then
+  enableval="$enable_htmllibdir"
   htmllibdir="$withval"
 else
   
@@ -2060,12 +2059,12 @@ for ac_hdr in dirent.h sys/ndir.h sys/dir.h ndir.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr that defines DIR""... $ac_c" 1>&6
-echo "configure:2064: checking for $ac_hdr that defines DIR" >&5
+echo "configure:2063: checking for $ac_hdr that defines DIR" >&5
 if eval "test \"`echo '$''{'ac_cv_header_dirent_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2069 "configure"
+#line 2068 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #include <$ac_hdr>
@@ -2073,7 +2072,7 @@ int main() {
 DIR *dirp = 0;
 ; return 0; }
 EOF
-if { (eval echo configure:2077: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:2076: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   eval "ac_cv_header_dirent_$ac_safe=yes"
 else
@@ -2098,7 +2097,7 @@ done
 # Two versions of opendir et al. are in -ldir and -lx on SCO Xenix.
 if test $ac_header_dirent = dirent.h; then
 echo $ac_n "checking for opendir in -ldir""... $ac_c" 1>&6
-echo "configure:2102: checking for opendir in -ldir" >&5
+echo "configure:2101: checking for opendir in -ldir" >&5
 ac_lib_var=`echo dir'_'opendir | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -2106,7 +2105,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-ldir  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 2110 "configure"
+#line 2109 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -2117,7 +2116,7 @@ int main() {
 opendir()
 ; return 0; }
 EOF
-if { (eval echo configure:2121: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:2120: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -2139,7 +2138,7 @@ fi
 
 else
 echo $ac_n "checking for opendir in -lx""... $ac_c" 1>&6
-echo "configure:2143: checking for opendir in -lx" >&5
+echo "configure:2142: checking for opendir in -lx" >&5
 ac_lib_var=`echo x'_'opendir | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -2147,7 +2146,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lx  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 2151 "configure"
+#line 2150 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -2158,7 +2157,7 @@ int main() {
 opendir()
 ; return 0; }
 EOF
-if { (eval echo configure:2162: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:2161: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -2181,12 +2180,12 @@ fi
 fi
 
 echo $ac_n "checking for ANSI C header files""... $ac_c" 1>&6
-echo "configure:2185: checking for ANSI C header files" >&5
+echo "configure:2184: checking for ANSI C header files" >&5
 if eval "test \"`echo '$''{'ac_cv_header_stdc'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2190 "configure"
+#line 2189 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 #include <stdarg.h>
@@ -2194,7 +2193,7 @@ else
 #include <float.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:2198: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:2197: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -2211,7 +2210,7 @@ rm -f conftest*
 if test $ac_cv_header_stdc = yes; then
   # SunOS 4.x string.h does not declare mem*, contrary to ANSI.
 cat > conftest.$ac_ext <<EOF
-#line 2215 "configure"
+#line 2214 "configure"
 #include "confdefs.h"
 #include <string.h>
 EOF
@@ -2229,7 +2228,7 @@ fi
 if test $ac_cv_header_stdc = yes; then
   # ISC 2.0.2 stdlib.h does not declare free, contrary to ANSI.
 cat > conftest.$ac_ext <<EOF
-#line 2233 "configure"
+#line 2232 "configure"
 #include "confdefs.h"
 #include <stdlib.h>
 EOF
@@ -2250,7 +2249,7 @@ if test "$cross_compiling" = yes; then
   :
 else
   cat > conftest.$ac_ext <<EOF
-#line 2254 "configure"
+#line 2253 "configure"
 #include "confdefs.h"
 #include <ctype.h>
 #define ISLOWER(c) ('a' <= (c) && (c) <= 'z')
@@ -2261,7 +2260,7 @@ if (XOR (islower (i), ISLOWER (i)) || toupper (i) != TOUPPER (i)) exit(2);
 exit (0); }
 
 EOF
-if { (eval echo configure:2265: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:2264: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   :
 else
@@ -2288,17 +2287,17 @@ for ac_hdr in unistd.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
-echo "configure:2292: checking for $ac_hdr" >&5
+echo "configure:2291: checking for $ac_hdr" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2297 "configure"
+#line 2296 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:2302: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:2301: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -2326,12 +2325,12 @@ done
 
 
 echo $ac_n "checking for working const""... $ac_c" 1>&6
-echo "configure:2330: checking for working const" >&5
+echo "configure:2329: checking for working const" >&5
 if eval "test \"`echo '$''{'ac_cv_c_const'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2335 "configure"
+#line 2334 "configure"
 #include "confdefs.h"
 
 int main() {
@@ -2380,7 +2379,7 @@ ccp = (char const *const *) p;
 
 ; return 0; }
 EOF
-if { (eval echo configure:2384: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:2383: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   ac_cv_c_const=yes
 else
@@ -2401,12 +2400,12 @@ EOF
 fi
 
 echo $ac_n "checking for size_t""... $ac_c" 1>&6
-echo "configure:2405: checking for size_t" >&5
+echo "configure:2404: checking for size_t" >&5
 if eval "test \"`echo '$''{'ac_cv_type_size_t'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2410 "configure"
+#line 2409 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #if STDC_HEADERS
@@ -2434,12 +2433,12 @@ EOF
 fi
 
 echo $ac_n "checking whether struct tm is in sys/time.h or time.h""... $ac_c" 1>&6
-echo "configure:2438: checking whether struct tm is in sys/time.h or time.h" >&5
+echo "configure:2437: checking whether struct tm is in sys/time.h or time.h" >&5
 if eval "test \"`echo '$''{'ac_cv_struct_tm'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2443 "configure"
+#line 2442 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #include <time.h>
@@ -2447,7 +2446,7 @@ int main() {
 struct tm *tp; tp->tm_sec;
 ; return 0; }
 EOF
-if { (eval echo configure:2451: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:2450: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   ac_cv_struct_tm=time.h
 else
@@ -2471,12 +2470,12 @@ fi
 for ac_func in getcwd mkdir strdup strstr
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&6
-echo "configure:2475: checking for $ac_func" >&5
+echo "configure:2474: checking for $ac_func" >&5
 if eval "test \"`echo '$''{'ac_cv_func_$ac_func'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2480 "configure"
+#line 2479 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char $ac_func(); below.  */
@@ -2499,7 +2498,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:2503: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:2502: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
@@ -2684,8 +2683,8 @@ s%@auth_incs@%$auth_incs%g
 s%@auth_libs@%$auth_libs%g
 s%@htmldir@%$htmldir%g
 s%@cgibindir@%$cgibindir%g
-s%@imagedir@%$imagedir%g
 s%@imageurl@%$imageurl%g
+s%@imagedir@%$imagedir%g
 s%@htmllibdir@%$htmllibdir%g
 s%@vpopuser@%$vpopuser%g
 s%@vpopgroup@%$vpopgroup%g
