Update all mentions of --with-htmllibdir to --enable-htmllibdir.
git-svn-id: http://svn.code.sf.net/p/qmailadmin/code/trunk@126 0199c96e-5249-4d07-b9ae-b85610bb9a6e

diff --git a/qmailadmin/configure b/qmailadmin/configure
--- a/qmailadmin/configure
+++ b/qmailadmin/configure
@@ -1484,13 +1484,13 @@ fi
 
 # Some tools Automake needs.
 
-ACLOCAL=${ACLOCAL-"${am_missing_run}aclocal"}
+ACLOCAL=${ACLOCAL-"${am_missing_run}aclocal-${am__api_version}"}
 
 
 AUTOCONF=${AUTOCONF-"${am_missing_run}autoconf"}
 
 
-AUTOMAKE=${AUTOMAKE-"${am_missing_run}automake"}
+AUTOMAKE=${AUTOMAKE-"${am_missing_run}automake-${am__api_version}"}
 
 
 AUTOHEADER=${AUTOHEADER-"${am_missing_run}autoheader"}
@@ -4576,8 +4576,8 @@ else
 
         if test "$htmllibdir" = ""
         then
-            { { echo "$as_me:$LINENO: error: Unable to find your htmllibdir directory, specify --with-htmllibdir." >&5
-echo "$as_me: error: Unable to find your htmllibdir directory, specify --with-htmllibdir." >&2;}
+            { { echo "$as_me:$LINENO: error: Unable to find your htmllibdir directory, specify --enable-htmllibdir." >&5
+echo "$as_me: error: Unable to find your htmllibdir directory, specify --enable-htmllibdir." >&2;}
    { (exit 1); exit 1; }; }
         fi
 
